# Generated by Django 4.2.3 on 2023-07-31 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('x_position', models.IntegerField()),
                ('y_position', models.IntegerField()),
                ('date_created', models.IntegerField()),
                ('date_updated', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('angle_start', models.IntegerField()),
                ('angle_end', models.IntegerField()),
                ('date_created', models.IntegerField()),
                ('date_updated', models.IntegerField()),
                ('from_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_people', to='surveillance_api.node')),
                ('to_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_people', to='surveillance_api.node')),
            ],
        ),
        migrations.AddField(
            model_name='node',
            name='partners',
            field=models.ManyToManyField(related_name='related_to', through='surveillance_api.Partner', to='surveillance_api.node'),
        ),
    ]
